### ISSUE TITLE
Features request: XSD support?

### ISSUE THREAD

**Issue by NeroBlackstone** [bhftbootcamp/Serde.jl#35]
I don't know if Serde.jl has the plan to support generating julia types from XSD and automatically add serialization code.

But in my opinion, this is more like a function that should be implemented by an independent package.

**Comment by dmitrii-doronin** [comment]
Hi, I think that sort of thing should be done no a higher level package, IMO. But, it's something I'm definitely looking forward to in Julia.

**Comment by dmitrii-doronin** [comment]
I'm closing this issue for now. There's a package that works well with XML. It might go public soon. Stay in touch)
