### ISSUE TITLE
Test case fails on julia 1.10

### ISSUE THREAD

**Issue by NeroBlackstone** [bhftbootcamp/Serde.jl#39]
In `test/deser.jl`, test case No.30:

> https://github.com/bhftbootcamp/Serde.jl/blob/6140ed063b0c4b2e73d31a86152c6febbcdeba18/test/deser.jl#L501-L504

In julia 1.10, it will fail:

```
Case №30: Deserializing missing and nothing: Test Failed at /home/nero/github/Serde.jl/test/deser.jl:501
  Expression: Serde.deser(Foo35_3, Dict{String, Any}("value" => 100))
    Expected: "WrongType: for 'Foo35_3' value '100' has wrong type 'value::Int64', must be 'value::Missing'"
     Message: "cannot convert a value to missing for assignment"

Stacktrace:
 [1] macro expansion
   @ ~/github/Serde.jl/test/deser.jl:501 [inlined]
 [2] macro expansion
   @ ~/.julia/juliaup/julia-1.10.3+0.x64.linux.gnu/share/julia/stdlib/v1.10/Test/src/Test.jl:1577 [inlined]
 [3] macro expansion
   @ ~/github/Serde.jl/test/deser.jl:472 [inlined]
 [4] macro expansion
   @ ~/.julia/juliaup/julia-1.10.3+0.x64.linux.gnu/share/julia/stdlib/v1.10/Test/src/Test.jl:1577 [inlined]
 [5] top-level scope
   @ ~/github/Serde.jl/test/deser.jl:7
```

This is because Julia 1.10 throw a different Error in `src/de/deser.jl`:

> https://github.com/bhftbootcamp/Serde.jl/blob/6140ed063b0c4b2e73d31a86152c6febbcdeba18/src/De/Deser.jl#L249-L251

If we test this function:

``` julia
deser(Missing,100)
```

Julia 1.10 will throw `ERROR: cannot convert a value to missing for assignment`

Julia 1.8 will throw `ERROR: MethodError: convert(::Type{Union{}}, ::Int64) is ambiguous. Candidates`

And in `src/de/deser.jl`, we are not handling `ErrorException`.

> https://github.com/bhftbootcamp/Serde.jl/blob/6140ed063b0c4b2e73d31a86152c6febbcdeba18/src/De/Deser.jl#L494-L515

# Question

How do you think it can be improved better? I can open a PR.

**Comment by NeroBlackstone** [comment]
A similar julia 1.10 test fail is No.37 in same test file.

```
Case №37: Deserialization Number to Number: Test Failed at /home/nero/github/Serde.jl/test/deser.jl:662
  Expression: Serde.deser_json(Message{Nothing}, exp_str)
    Expected: "WrongType: for 'Message{Nothing}' value 'Dict{String, Any}()' has wrong type 'payload::Dict{String, Any}', must be 'payload::Nothing'"
     Message: "cannot convert a value to nothing for assignment"

Stacktrace:
 [1] macro expansion
   @ ~/github/Serde.jl/test/deser.jl:662 [inlined]
 [2] macro expansion
   @ ~/.julia/juliaup/julia-1.10.3+0.x64.linux.gnu/share/julia/stdlib/v1.10/Test/src/Test.jl:1577 [inlined]
 [3] macro expansion
   @ ~/github/Serde.jl/test/deser.jl:655 [inlined]
 [4] macro expansion
   @ ~/.julia/juliaup/julia-1.10.3+0.x64.linux.gnu/share/julia/stdlib/v1.10/Test/src/Test.jl:1577 [inlined]
 [5] top-level scope
   @ ~/github/Serde.jl/test/deser.jl:7
```

**Comment by dmitrii-doronin** [comment]
Hi, @NeroBlackstone! I've seen this issue before and I have not been able to pinpoint the root cause. If you do plain conversion, outside of the package, it will work just fine. This behaviour sprung up after 1.10 release. 

Currently it tries to convert after return (there's a specific syntax for that). I think, the solution would be to switch to explicit conversion within functions before return.

**Comment by NeroBlackstone** [comment]
I find the reason,[ `convert()` throws inconsistent errors](https://github.com/JuliaLang/julia/issues/51655) in Julia 1.10.

I think the simplest solution is:

``` julia
elseif (e isa MethodError) || (e isa InexactError) || (e isa ArgumentError) || (e isa ErrorException)
```

I have tested it and all passed, what do you think?

**Comment by dmitrii-doronin** [comment]
Have you tried explicit conversions? I think it might take more time but be more sustainable in the long run. 

Also I'm baffled by the policy. It's not julia 2.0 to break existing error behaviours)

**Comment by dmitrii-doronin** [comment]
Also, @gryumov what's your stand on this? Apparently, there's an issue already on the official page.

**Comment by NeroBlackstone** [comment]
> Also I'm baffled by the policy. It's not julia 2.0 to break existing error behaviours) 

“Error types, unless explicitly documented (like DomainError or Base.IOError), are subject to change is the official policy”

Looks like they don't think this is a break change.😅

I don’t know if subsequent Julia versions will maintain this behavior.

**Comment by dmitrii-doronin** [comment]
There're two types of syntaxes for converting. It seems like the first one's behaviour has changed. Switching to the second type should enforce the correct behaviour. 

```julia
function test(a::Int64)::Float64 
    return a
end

# or

function test(a::Int64)
    return Float64(a)
end
```

I would try to stay clear of any functions that are called implicitly here. Might introduce some complicated bugs, IMO.

**Comment by dmitrii-doronin** [comment]
Okay, I see where the issue is. I'm taking a look. You can comment out these tests if you're actively developing. They don't affect the core functionality.

**Comment by gryumov** [comment]
Hello everyone! @dmitrii-doronin it might seem strange #40, but we need to deal with multiple dispatch, let's create issues for this:


https://github.com/bhftbootcamp/Serde.jl/actions/runs/8912634371/job/24476466918?pr=40
